# Build uYouPlus using YouTube v16

name: Build v16

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env: 
  # UYOU_VERSION is dynamic
  YOUTUBE_VERSION: "16.42.3"
  YOUTUBE_URL: "https://objects.n23.io/4bcb968ea2654ee1be650d6be455725e:bucket1/YouTube_16.42.3.ipa"
  THEOS: ${{ github.workspace }}/theos
  GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build uYouPlus
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v3
        with:
          path: main
          submodules: recursive
          
      - name: Get uYou version
        run: | 
          brew install grep
          curl -s "https://raw.githubusercontent.com/MiRO92/uYou-for-YouTube/main/README.md" 2>&1 | ggrep -Po "https:\/\/miro92\.com\/repo\/depictions\/com\.miro\.uyou\/iPA\/YouTube_[0-9.]*_uYou_[0-9.]*\.ipa" | ggrep -Po "uYou_[0-9.]*[^.ipa]" | head -1 | tr -d "uYou_"
          UYOU_VERSION="${{ github.event.inputs.foo }}"
          echo "UYOU_VERSION=${UYOU_VERSION}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: brew install ldid dpkg

      - name: Setup Theos
        uses: actions/checkout@v3
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: Download iOS 15 SDK
        run: |
          curl -LO https://github.com/chrisharper22/sdks/archive/main.zip
          TMP=$(mktemp -d)
          unzip -qq main.zip -d $TMP
          mv $TMP/sdks-main/*.sdk $THEOS/sdks
          rm -r main.zip $TMP
          

      - name: Setup Theos Jailed
        uses: actions/checkout@v3
        with:
          repository: kabiroberai/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install

      - name: Download uYou & prepare YouTube iPA
        run: |
          curl "https://raw.githubusercontent.com/Muirey03/RemoteLog/master/RemoteLog.h" --output "$THEOS/include/RemoteLog.h"
          curl "https://miro92.com/repo/debs/com.miro.uyou_${{ env.UYOU_VERSION }}_iphoneos-arm.deb" --output "./main/Tweaks/uYou/com.miro.uyou_${{ env.UYOU_VERSION }}_iphoneos-arm.deb"
          wget "$YOUTUBE_URL" --no-verbose -O ./main/YouTube.ipa
          dpkg-deb -x "./main/Tweaks/uYou/com.miro.uyou_${{ env.UYOU_VERSION }}_iphoneos-arm.deb" ./main/Tweaks/uYou/
          unzip -q ./main/YouTube.ipa -d ./main/tmp
          rm -rf ./main/tmp/Payload/YouTube.app/PlugIns/*
          cp -R ./main/Extensions/*.appex ./main/tmp/Payload/YouTube.app/PlugIns

      - name: Fix compiling && Build Package
        id: build_package
        run: |
          cd ${{ github.workspace }}/main
          (cd ${{ github.workspace }}/main/Tweaks/YouPiP && sed -i '' "14s/$/ AVFoundation UIKit/" Makefile)
          make package FINALPACKAGE=1
          (mv "packages/$(ls -t packages | head -n1)" "packages/uYouPlus_${{ env.YOUTUBE_VERSION  }}_${{ env.UYOU_VERSION }}.ipa")
          echo "::set-output name=package::$(ls -t packages | head -n1)"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: uYouPlus_${{ env.YOUTUBE_VERSION  }}_${{ env.UYOU_VERSION }}
          path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1          
        with:
          tag_name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-(${{ github.run_number }})
          release_name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-(${{ github.run_number }})
          draft: true
          prerelease: true

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          asset_name: uYouPlus_${{ env.YOUTUBE_VERSION  }}_${{ env.UYOU_VERSION }}.ipa
          asset_content_type: application/vnd.debian.binary-package
